var _2014 = {
	songs: [
["Akdong Musician","200%","0Oi8jDMvd_w"],
["Sistar","Touch My Body","Q33SoblaZbU"],
["Soyou & Jung Gi Go","Some (썸)","Y-FhDScM_2w"],
["Epik High featuring Cho Won Sun of Rollercoaster","Happen Ending (헤픈엔딩)","_78JiWS6fUA"],
["Kim Dong-ryool","How I Am (그게나야)","4GW7xwZkDsY"],
["2NE1","Come Back Home","vLbfv-AAyvQ"],
["MC Mong featuring Jinsil of Mad Soul Child","Miss Me Or Diss Me (내가 그리웠니)","-6OxVfem0WM"],
["Winner","Empty (공허해)","gEqlF5N8UMs"],
["Jung-in & Gary","Your Scent (사람냄새)","DrxZbkOB5PI"],
["Postmen","Can't Go to Shinchon (신촌을 못가)","kovTTwKz5cU"],
["Fly to the Sky","You You You (너를 너를 너를)","b_5AkvUN6EI"],
["g.o.d.","The Lone Duckling (미운 오리 새끼)","qXrcNXObJRo"],
["Park Hyo-shin","Happy Together","kYCW7Ea9p1E"],
["Toy featuring Sung Si-kyung","Three of Us (세 사람)","4Pax5vCQbMA"],
["Taeyang","Eyes, Nose, Lips (눈, 코, 입)","UwuAPyOImoI"],
["Idina Menzel","Let It Go","0QVJZ_LVDIw"],
["Gary featuring Crush","Shower Later (조금 이따 샤워해)","tgfuaDS-S2c"],
["Girls' Generation","Mr.Mr.","Z8j_XEn9b_8"],
["Jang Beom-Jun","Difficult Woman (어려운 여자)","hKFtA1g1CAU"],
["Younha","Umbrella (우산)","kTVvtlfU-Ts"],
["Hyolyn","Hello (안녕)","TW2IBVctARE"],
["Jung Seung-hwan","I Want to Fall in Love (사랑에 빠지고 싶다)","n5OosJIXhfk"],
["Huh Gak & Jung Eun-ji","Break Up to Make Up (이제 그만 싸우자)","BIbTM4bZHUM"],
["Girl's Day","Darling","QB4dQcxgJPY"],
["Hi Suhyun featuring Bobby","I'm Different (나는 달라)","2zwTaT0JeOY"],
["Ailee","Singing Got Better (노래가 늘었어)","ZcID0Wn4zwI"],
["San E featuring Bumkey","Body Language","WR6x_BfoZq0"],
["Park Hyo-shin","Wild Flower (야생화)","_hsrsmwHv0A"],
["15&","Can't Hide It (티가 나나봐)","WIfwWS6nHFg"],
["MC the Max","We Back Then (그대가 분다)","xo5BbQzlxyE"],
["Bro","That Kind of Guy (그런 남자)","YPqKCnL8eJY"],
["Beast","No More (이젠 아니야)","5HwjMySsKJA"],
["Sistar","I Swear","8PrNPhVexE4"],
["Beast","Good Luck","Hs8QGv2VqJA"],
["Jung Gi Go featuring Beenzino","Want U (너를 원해)","Xteny-dgr4I"],
["Sung Si-kyung, Kwon Jin-ah","Don't Forget (잊지 말기로 해)","8mw4SdN4J3s"],
["Akdong Musician","Time and Fallen Leaves (시간과 낙엽)","kiKwuz85Ar4"],
["Yoon Mi-rae","I Love You (너를 사랑해)","CxiWHe-waAM"],
["Lee Chi Hyun and Friends","Only You (당신만이)","j3yaqALBq1s"],
["4Minute","Whatcha Doin' Today? (오늘 뭐해?)","4xLFxfXWDUk"],
["San E, Raina","A Midsummer Night's Sweetness (한여름밤의 꿀)","nkfMN-jaycA"],
["Exo","December, 2014 (The Winter's Tale)","3Y5B3Ehrmps"],
["IU & HIGH4","Not Spring, Love or Cherry Blossoms (봄,사랑,벚꽃 말고)","ouR4nn1G9r4"],
	]
};