var _2016 = {
	songs: [
		["Twice","Cheer Up","c7rCyll5AeY"],
		["Suzy, Baekhyun","Dream","WfYgbFBFe1E"],
		["GFriend","Navillera (너 그리고 나)","Se8bbsUFjC8"],
		["Wonder Girls","Why So Lonely","PYGODWJgR-c"],
		["Zico","I Am You, You Are Me (너는 나 나는 너)","ewjucLierFc"],
		["Akdong Musician","RE-BYE","ST8O-AeY3Uo"],
		["Baek A-yeon","so-so (쏘쏘)","W1CDOQv-ZgU"],
		["Jung Eun-ji featuring Hareem","Hopefully Sky (하늘바라기)","nzDO6tAB6ng"],
		["Taeyeon","Rain","eHir_vB1RUI"],
		["Lee Hi","Breathe (한숨)","CU3rvajFdbg"],
		["10cm","What the spring?? (봄이 좋냐??)","cIGgSI1uhKI"],
		["Sistar","I Like That","LJVUjmNMF8c"],
		["Junsu","How Can I Love You","kTCmv8_AnhM"],
		["Mad Clown feat. Kim Na-young","Once Again (다시 너를)","YYXognEO-P4"],
		["GFriend","Rough (시간을 달려서)","0VKcLPdY9lI"],
		["Mamamoo","You're the Best (넌 is 뭔들)","QbhmTM1cRro"],
		["Urban Zakapa","I Don't Love You (널 사랑하지 않아)","MfYPKZl7W1w"],
		["K.Will","Talk Love (말해! 뭐해?)","iXQy6sMcRcw"],
		["Exo","Monster","KSH-FVVtTf0"],
		["Jang Beom-Jun","Fallen in Love (Only With You) (사랑에 빠졌죠 (당신만이))","TS0nVS6xI3E"],
		["Gary featuring Gaeko","Lonely Night (또 하루)","tr6Xi0DNWj8"],
		["Chen, Punch","Everytime","fTc5tuEn6_U"],
		["Simon Dominic, Gray, One","Comfortable (맘 편히)","a7ePM0KYjHA"],
		["Loco, GRAY featuring ELO","GOOD","pomcpYotKgA"],
	]
};