var _2015 = {
	songs: [
	["Park Myeong-soo, IU","Leon (레옹)","8jkOzXVQi9I"],
	["Big Bang","Loser","1CTced9CMMk"],
	["Big Bang","Let's Not Fall In Love (우리 사랑하지 말아요)","9jTo6hTZmiQ"],
	["IU","Twenty-three (스물셋)","42Gtm4-Ax2U"],
	["Miss A","Only You (다른 남자 말고 너)","zO9RzrhYR-I"],
	["Park Jin-young featuring Jessi","Who's Your Mama? (어머님이 누구니)","kUGQ7Tz4os0"],
	["Big Bang","Bang Bang Bang (뱅뱅뱅)","2ips2mM7Zqw"],
	["Gary featuring Miwoo","Get Some Air (바람이나 좀 쐐)","JojOd079xwQ"],
	["Naul","You from the Same Time (같은 시간 속의 너)","Q_YdBd05FJs"],
	["IU","Heart (마음)","A7PoMDw18qs"],
	["Taeyeon featuring Verbal Jint","I","4OrCA1OInoo"],
	["Sistar","Shake It","x9-TIy7WPQI"],
	["Big Bang","If You","H0eT9omRQS0"],
	["Zion.T","No Make Up","eqcte1r3aiQ"],
	["MC Mong featuring Chancellor of The Channels","Love Mash (사랑범벅)","Z2_PlMn8ZtY"],
	["Psy featuring CL","Daddy","FrG4TEcSuRg"],
	["iKON","My Type (취향저격)","ZS6vfv4sszg"],
	["Yoon Mi-rae","This Is Love (사랑이 맞을거야)","ONACez-twhc"],
	["Zico featuring Babylon","Boys and Girls","UsaJsymfuWU"],
	["Girls' Generation","Party","HQzu7NYlZNQ"],
	["Oh Hyuk","A Little Girl (소녀)","bLoO0FSXncg"],
	["Zico featuring Zion.T","Eureka","xp35Dwy4hHM"],
	["Huh Gak","Snow of April (사월의 눈)","7u_o28xwBHI"],
	["Im Chang-jung","Love Again (또 다시 사랑)","LDGO2nVf_dM"],
	["Jeong Seung-hwan, Park Yoon-ha","I Have To Forget You (슬픔 속에 그댈 지워야만 해)","WshkdJMiaw8"],
	["Zion.T and Crush","Just (그냥)","Skhwqq-iGQM"],
	["iKON","Apology (지못미)","blSCDrx0CDA"],
	["Incredivle, Tablo, Jinusean","Oppa's Car (오빠차)","6oI487adZKY"],
	["hyukoh","Come and Goes (와리가리)","ECMc1SB60E0"],
	["Zion.T","Yanghwa BRDG (양화대교)","uLUvHUzd4UA"],
	["Mad Clown featuring Jinsil of Mad Soul Child","Fire (화)","hfEf6NFS81E"],
	["4Men","Let's Hug (안아보자)","nG4L404vGyU"],
	["Turbo","Again (다시)","6tPrej8Qdr0"],
	["Shin Jimin featuring Iron","Puss","KEaBq-XB4FY"],
	["Davichi","Cry Again (또 운다 또)","s2rw4_2XCTg"],
	["Baek A-yeon featuring Younghyun","Shouldn't Have (이럴거면 그러지말지)","x815A21RIto"],
	["hyukoh","Wi Ing Wi Ing (위잉위잉)","hr4GaRPX6cM"],
	["Jonghyun","Deja-Boo (데자-부)","TcvDR5xz97g"],
	["EXO","Love Me Right","RuqaVryDRd0"],
	["Shinee","View","UF53cptEE5k"],
	["EXID","Up & Down (위아래)","hfXZ6ydgZyo"],
	]
};