var _2011 = {
	songs: [
		
["IU","You and I (너랑 나)","NJR8Inf77Ac"],
["GG (Park Myeong-su & G-Dragon) feat. Park Bom","Having an Affair (바람났어)","NI4KMiDapLU"],
["Davichi","Don't Say Goodbye (안녕이라고 말하지마)","CuwRqIzkyOQ"],
["Leessang feat. Yoon Mi-rae and Kwon Jung-yeol","I Turned Off the TV... (TV를 껐네...)","-HxaERgTNwY"],
["Miss A","Good-bye Baby","EYKO1za5mX0"],
["T-ara","Cry Cry","5M69TE1yzt4"],
["Ulala Session","The Western Sky (서쪽 하늘)","0x5EMz9WBkw"],
["Kim Bum-soo","Please (제발)","N6vywZgm0Cw"],
["Wonder Girls","Be My Baby","3fy4cqWMhyI"],
["IU","The Story Only I Didn't Know (나만 몰랐던 이야기)","qGWZUtfV3IU"],
["Girls' Generation","The Boys","6pA_Tou-DPI"],
["2NE1","I Am the Best (내가 제일 잘 나가)","j7_lSP8Vc3o"],
["G.NA","Black & White","ntkLP26htZA"],
["Jung Yong-hwa","For First Time Lovers (Banmal Song) (처음 사랑하는 연인들을 위해 (반말송)","hS4L6WBjEkE"],
["IU","Good Day (좋은 날)","jeqdYqsrsA0"],
["Busker Busker","Tokyo Girl (동경소녀)","Ugmif2uglCo"],
["Brown Eyed Girls","Sixth Sense","pIqkDBsSJOw"],
["Kim Yeon-woo","If You Were Like Me (나와 같다면)","Lt8QqNVc3Jc"],
["2PM","Hands Up","KgrB2KBZws4"],
["Girls' Generation","The Boys","6pA_Tou-DPI"],
["Huh Gak","Hello","yY7dRwJnJZ0"],
["Park Bom","Don't Cry","ypit0NcNV-8"],
["Ulala Session feat. Christina","Open Arms","3cK5WWnf1JQ"],
["Sistar","So Cool","Pj3q0ZChgFE"],
["Ock Joo-hyun","For 1000 Days (천일동안)","N057YxkuX1E"],
["f(x)","Danger (피노키오)","kKS12iGFyEA"],
["Park Jung-hyun","I Hope It Would Be That Way Now (이젠 그랬으면 좋겠네)","zuoJNKZ_8so"],
["JK Kim Dong-wook","Coordination (조율)","TpvjGVtyNGU"],
["IU","Someday","403ezTArPRk"],
["Hyun Bin","That Man (그 남자)","Yd3QQS7GIX0"],
["Davichi & T-ara","We Were in Love (우리 사랑했잖아)","tf0P6tAYmcU"],
["2NE1","Lonely","5n4V3lGEyG4"],
["2NE1","Ugly","NGe0hHvAGkc"],
["CN Blue","Intuition (직감)","_500iqJggs0"],
["Huh Gak","Don’t Forget Me (나를 잊지 말아요)","4hDERN69-TI"],
["K.Will","My Heart Beating (가슴이 뛴다)","KFSzMegd7hs"],
["Big Bang","Love Song","IKZEmLvYVF0"],
["HyunA & Hyunseung","Trouble Maker","s-zRAQmKUkI"],
["Big Bang","Tonight","8d5QEWdHchk"],
["Song Jieun feat. Bang Yong-guk","Going Crazy (미친거니)","n1TLaZp1i8E"],
	
	]
};