var _2013 = {
	songs: [
		["Psy","Gentleman","ASO_zypdnsQ"],
["Busker Busker","Love, At First (처음엔 사랑이란게)","KEk98JAPt80"],
["Roy Kim","Spring Spring Spring (봄봄봄)","k3-BDy55tq4"],
["Sistar","Give It to Me","p6XLNsJ9YrA"],
["Baechigi featuring Ailee","Shower of Tears (눈물샤워)","8uzynbfAaFM"],
["Akdong Musician","Crescendo","Kv9SWA713GA"],
["Sistar19","Gone Not Around Any Longer (있다 없으니까)","JtVhwsACgTw"],
["Park Myeong Su & Primary (featuring Gaeko)","I Got C","mQwxOxxhoC0"],
["Soyou & Mad Clown","Stupid In Love (착해 빠졌어)","ZZioyEsv4P4"],
["IU","The Red Shoes (분홍신)","Q0xvVgKJxfs"],
["Lee Hyori","Miss Korea (미스코리아)","Huu3H5ei_-8"],
["Ailee","U&I","c4_rwTytAOs"],
["Jung Hyung Don","Gangbuk Cool Guy (강북멋쟁이)","379NjchCjzw"],
["2NE1","Falling in Love","zEVd9pSG85Q"],
["Dynamic Duo featuring Muzie of UV","BAAAM","DmAHmYgdopw"],
["Leessang featuring Yoojin of The SeeYa","Tears (눈물)","77qAgl1SCPk"],
["G-Dragon","Who You? (니가 뭔데)","cnevlbEy-Qo"],
["Davichi featuring Verbal Jint","Be Warmed (녹는 중)","1KtpinQW1DM"],
["Trouble Maker","Now (내일은 없어)","6pw972Kl3L0"],
["f(x)","Rum Pum Pum Pum (첫 사랑니)","xnku4o3tRB4"],
["Girls' Generation","I Got a Boy","wq7ftOZBy0E"],
["Lee Hyori","Bad Girls","kLyfHxNDeVM"],
["Yoon Mi Rae (Tasha)","Touch Love (터치 러브)","ZH8BYNwmR5Q"],
["Davichi","Turtle (거북이)","ykAoxJCZG8w"],
["Davichi","The Letter (편지)","YVLIn6xMSh0"],
["2NE1","Missing You (그리워해요)","AG0jlKdB1s0"],
["Seo In-guk & Zia","Loved You (이별남녀)","e1gfJfXbaKs"],
["K.Will","You Don't Know Love (촌스럽게 왜 이래)","alZ9hvgfIk4"],
["Shinee","Dream Girl","vhxjEXDAy6s"],
["Sung Si-kyung, Park Hyo-shin, Seo In-guk, VIXX & Yeo Dong-saeng","Winter Propose (겨울 고백)","UvwICcKfWsA"],
["Jung Eun-ji & Huh Gak","Short Hair (짧은머리)","awbuHGf5Z7I"],
["Beast","Will You Be Okay? (괜찮겠니)","aLn7Iq-z-bA"],
["San E","Story of Someone I Know (아는사람 얘기)","eVdjb3AtKpM"],
["Hyolyn","One Way Love (너 밖에 몰라)","0CbE3SqbOdY"],
["Lee Seung Chul","My Love","hXiCB6SZp4U"],
["Bumkey featuring Dynamic Duo","Attraction (갖고놀래)","ytelLXvjWBw"],
["Lee Hi","Rose","Ff_SuAzll90"],
["IU","Friday (금요일에 만나요)","EiVmQZwJhsA"],
["Huh Gak featuring Swings","That You’re Mine (넌 내꺼라는걸)","f1brqMdv-gE"],
["Shinee","Everybody","hKbNV-4b_g8"],
["The One","Winter Love","aqrrYyFll8E"],
["Beenzino","Dali, Van, Picasso","c2NSZInZ3XQ"],
["4Minute","What's Your Name? (이름이 뭐에요?)","H-IJWqIHioA"],

	]
};