var _2010 = {
	songs: [
		["miss A","Bad Girl Good Girl","8TeeJvcBdLA"],
		["Ga In and Jo Kwon","We Fell in Love (우리 사랑하게 됐어요)","_WzrW4HVAhk"],
		["Wonder Girls","2 Different Tears","Rxh3_sr5UAE"],
		["IU with. Seulong","Nagging (잔소리)","dCJ10QcaUes"],
		["IU","Good Day (좋은 날)","jeqdYqsrsA0"],
		["2AM","Can't Let You Go Even If I Die (죽어도 못 보내)","hOREkPq1aVQ"],
		["Kara","Lupin (루팡)","j7TYiyEhxdI"],
		["T-ara","I Go Crazy Because of You (너 때문에 미쳐)","udwxhXhR0H0"],
		["Girls' Generation","Run Devil Run","q_gfD3nvh-8"],
		["2NE1","Go Away","3yW13T2sfKg"],
		["Huh Gak","Always (언제나)","LYLk-y-8jaw"],
		["Girls' Generation","Oh!","TGbwL8kSpEk"],
		["2NE1","Try to Follow Me (날 따라 해봐요)","0q62LBAbphk"],
		["Rain","Love Song (널 붙잡을 노래)","_xHfAjfIdYo"],
		["Lee Hyori feat. Gary","Swing (그네)","2SYu5TVW4a8"],
		["Lee Hyori feat. Ceejay","Chitty Chitty Bang Bang","A3x2nKc2ZoM"],
		["2PM","Without U","pB4920B2l5g"],
		["Seo Young Eun feat. Jung Yup","Spiteful Words (이 거지같은 말)","_ARXGKtzgKs"],
		["f(x)","Nu ABO (NU 예삐오)","E8ZrPFMr_nY"],
		["Davichi","Time Please Stop (시간아 멈춰라)","PcryoN4s3Sk"],
		["MC Mong feat. Mellow","Sick Enough to Die (죽을 만큼 아파서)","cAr-rhGkXzY"],
		["DJ DOC","I'm a Guy Like This (나 이런사람이야)","ycp1s9UmpQc"],
		["HOMME (Changmin & Lee Hyun)","I Was Able to Eat Well (밥만 잘 먹더라)","530z_frEMqk"],
		["Secret","Madonna","EPHUZenprKc"],
		["HOMME (Changmin & Lee Hyun)","I Was Able to Eat Well (밥만 잘 먹더라)","530z_frEMqk"],
		["F.T Island","Love Love Love (사랑 사랑 사랑)","kWIpynw5cHI"],
		["Supreme Team feat. Young Jun","Why (왜)","TlBkm6gZ93U"],
		["Sung Si Kyung feat. IU","It's You (그대네요)","5VkWJ_mB-Ts"],
		["Supreme Team feat. Young Jun","Then Then Then (그땐 그땐 그땐)","evn7MgjuTss"],
		["Ga In","Irreversible (돌이킬 수 없는)","bN_so3176AA"],
		["Kang Seung Yoon","By Instinct (본능적으로) (feat. Swings)","h1GMAX-0ico"],
		["Girls' Generation","Hoot (훗)","TGbwL8kSpEk"],
		["2AM","You Wouldn't Answer My Calls (전활 받지 않는 너에게)","ozpCXhAyeqM"],
		["Taeyeon & The One","Like A Star (별처럼)","eIKlrQ-r2xc"],
		["Browneyed Soul","If It's Same (똑같다면)","3mh9rn-KItw"],
	]
};