var _2012 = {
	songs: [
	["PSY","Gangnam Style (강남스타일)","9bZkp7q19f0"],
	["Big Bang","Blue","2GRP1rkE4O0"],
	["Lee Hi","1, 2, 3, 4","1AI7UP1iRAU"],
	["Lee Seung-gi","Return (되돌리다)","Xw0URnMrFV8"],
	["Naul","Memory Of The Wind (Korean:바람기억)","f5ShDNOqq1E"],
	["T-ara","Lovey-Dovey","CJ0djllyqwY"],
	["Busker Busker","Cherry Blossom Ending (벚꽃 엔딩)","tXV7dfvSefo"],
	["Sistar","Alone (나 혼자)","E0ZHXVp_wUE"],
	["Girls' Generation-TTS","Twinkle","JmM04_OgajU"],
	["Big Bang","Monster","btDd9rOlc2k"],
	["IU","Every End of the Day (하루 끝)","G2_4SZlt4jM"],
	["Jung Eun-ji & Seo In-guk","All for You","bCW_p_fHDQo"],
	["Busker Busker","If You Really Love Me (정말로 사랑한다면)","6SKunZTZzXc"],
	["2AM","I Wonder If You Hurt Like Me (너도 나처럼)","OhuVWznRDDs"],
	["f(x)","Electric Shock","n8I8QGFA1oM"],
	["Jeong Jun-ha","The Story of a Tall Bachelor (키 큰 노총각 이야기)","gHK9ibnKm3g"],
	["Epik High feat. Lee Hi","It's Cold","SK-xhoe3nLM"],
	["Baek Ji-young featuring Gary of Leessang","Voice (목소리)","z1jSqbZMcxA"],
	["Jung Joon Young & Roy Kim","Becoming Dust (먼지가 되어)","pd5nkMi8c_c"],
	["Shinee","Sherlock (Clue + Note)","8kyG5tTZ1iE"],
	["Se7en","When I Can't Sing (내가 노래를 못해도)","dQwEM6W9kUI"],
	["2NE1","I Love You","LUrUPzLm5SI"],
	["Hyuna","Ice Cream","QlWZluzBNxM"],
	["Sistar","Loving U","oL2AlXWVbKU"],
	["G-Dragon","That XX (그 XX)","j57IzkTFnT8"],
	["K.Will","I Need You (니가 필요해)","vpOau9ZxQNY"],
	["Beast","I Knew It (이럴 줄 알았어)","W9yHu5g9IQU"],
	["Huh Gak featuring Zia","I Need You","rTQH3EnAt7o"],
	["Lyn","Back In Time (시간을 거슬러)","tn5BvWWdjkY"],
	["CN Blue","Hey You","hZYuZ5DIvn4"],
	["Sung Si-kyung, Park Hyo-shin, Lee Seok-hoon, Seo In-guk, VIXX","Because It's Christmas (크리스마스니까)","YaYC2uW0PLM"],
	["Girls' Generation","Dancing Queen","EXZxc8GSXnI"],
	["Akdong Musician","You Are Attractive (매력있어)","1UIVifr0RKE"],
]
};